"""
Exports a trained lens LSTM to a Lua string-blob weights module and verifies
numpy<->torch parity before deploy (PASS < 1e-5, same bar as
ml/Deploy/export_policy_weights.py).

String-blob format is required, not stylistic: 2x64 LSTM over 17 inputs is
~54.8k numbers, close enough to LuaJIT's 65,536 constants-per-prototype cap
that inline tables are unsafe.

PyTorch LSTM gate order is i,f,g,o in chunks of hidden.
"""
import argparse
import re
from pathlib import Path

import numpy as np
import torch

SCRIPT_DIR = Path(__file__).resolve().parent
EXP_DIR = SCRIPT_DIR / "experiments"
MOD_CTRL = SCRIPT_DIR / "mod" / "lstm_abs" / "lua" / "vehicle" / "controller"
DRIVE_CTRL = Path(r"<home>\AppData\Local\BeamNG\BeamNG.drive\current\mods"
                  r"\Unpacked\lstm_abs\lua\vehicle\controller")

HIDDEN = 64
CLIP_OBS = 10.0


def blob(arr):
    return " ".join(f"{v:.9g}" for v in np.asarray(arr).ravel(order="C"))


def emit_lua(ckpt, lens):
    sd = ckpt["model"]
    mean = np.asarray(ckpt["feat_mean"], dtype=np.float64)
    std = np.asarray(ckpt["feat_std"], dtype=np.float64)
    car_max = ckpt["car_max"]
    in_cols = ckpt["input_cols"]

    parts = [
        "-- generated by export_lstm_abs.py - do not edit by hand",
        "local M = {}",
        f'M.lens = "{lens}"',
        f"M.input_dim = {len(in_cols)}",
        f"M.hidden = {HIDDEN}",
        "M.output_dim = 4",
        f"M.seq_len = {ckpt['seq_len']}",
        f"M.clip_obs = {CLIP_OBS}",
        'M.output = "fraction_of_car_max"',
        f'M.sensor_src = "{ckpt.get("sensor_src", "ffi")}"',
        "M.zero_idx = {" + ", ".join(str(in_cols.index(c) + 1)
                                     for c in (ckpt.get("zero_cols") or [])) + "}",
        f"M.input_cols = {{{', '.join(chr(34) + c + chr(34) for c in in_cols)}}}",
        f"M.mean_s = [==[{blob(mean)}]==]",
        f"M.std_s = [==[{blob(std)}]==]",
        "M.car_max = {",
    ]
    for car, mx in car_max.items():
        parts.append(f"  [\"{car}\"] = {{{', '.join(f'{v:.9g}' for v in np.asarray(mx))}}},")
    parts.append("}")

    parts.append("M.layers = {")
    for l in range(2):
        w_ih = sd[f"lstm.weight_ih_l{l}"].cpu().numpy().astype(np.float64)
        w_hh = sd[f"lstm.weight_hh_l{l}"].cpu().numpy().astype(np.float64)
        b_ih = sd[f"lstm.bias_ih_l{l}"].cpu().numpy().astype(np.float64)
        b_hh = sd[f"lstm.bias_hh_l{l}"].cpu().numpy().astype(np.float64)
        parts += [
            "  {",
            f"    in_dim = {w_ih.shape[1]}, hidden = {HIDDEN},",
            f"    w_ih_s = [==[{blob(w_ih)}]==],",
            f"    w_hh_s = [==[{blob(w_hh)}]==],",
            f"    b_ih_s = [==[{blob(b_ih)}]==],",
            f"    b_hh_s = [==[{blob(b_hh)}]==],",
            "  },",
        ]
    parts.append("}")

    hw = sd["head.weight"].cpu().numpy().astype(np.float64)
    hb = sd["head.bias"].cpu().numpy().astype(np.float64)
    parts += [
        "M.head = {",
        f"  rows = {hw.shape[0]}, cols = {hw.shape[1]},",
        f"  w_s = [==[{blob(hw)}]==],",
        f"  b_s = [==[{blob(hb)}]==],",
        "}",
        "return M",
        "",
    ]
    return "\n".join(parts)


def parse_blob(text, key):
    m = re.search(rf"{key}\s*=\s*\[==\[(.*?)\]==\]", text, re.S)
    if not m:
        raise ValueError(f"missing {key}")
    return np.fromstring(m.group(1), sep=" ")


def lua_forward(text, seq):
    """numpy mirror of the Lua loop order - the parity reference."""
    mean = parse_blob(text, "M.mean_s")
    std = parse_blob(text, "M.std_s")
    in_dim = int(re.search(r"M\.input_dim = (\d+)", text).group(1))

    layer_blocks = re.findall(r"in_dim = (\d+), hidden = (\d+),\s*"
                              r"w_ih_s = \[==\[(.*?)\]==\],\s*"
                              r"w_hh_s = \[==\[(.*?)\]==\],\s*"
                              r"b_ih_s = \[==\[(.*?)\]==\],\s*"
                              r"b_hh_s = \[==\[(.*?)\]==\],", text, re.S)
    layers = []
    for ind, hid, wih, whh, bih, bhh in layer_blocks:
        ind, hid = int(ind), int(hid)
        layers.append({
            "in": ind, "h": hid,
            "w_ih": np.fromstring(wih, sep=" ").reshape(4 * hid, ind),
            "w_hh": np.fromstring(whh, sep=" ").reshape(4 * hid, hid),
            "b_ih": np.fromstring(bih, sep=" "),
            "b_hh": np.fromstring(bhh, sep=" "),
        })
    hm = re.search(r"M\.head = \{\s*rows = (\d+), cols = (\d+),\s*"
                   r"w_s = \[==\[(.*?)\]==\],\s*b_s = \[==\[(.*?)\]==\],", text, re.S)
    rows, cols = int(hm.group(1)), int(hm.group(2))
    hw = np.fromstring(hm.group(3), sep=" ").reshape(rows, cols)
    hb = np.fromstring(hm.group(4), sep=" ")

    zm = re.search(r"M\.zero_idx = \{([^}]*)\}", text)
    zidx = [int(x) - 1 for x in zm.group(1).split(",") if x.strip()] if zm else []
    sig = lambda z: 1.0 / (1.0 + np.exp(-z))
    h = [np.zeros(l["h"]) for l in layers]
    c = [np.zeros(l["h"]) for l in layers]
    for t in range(seq.shape[0]):
        row = seq[t].copy()
        for zi in zidx:
            row[zi] = 0.0
        x = np.clip((row - mean) / std, -CLIP_OBS, CLIP_OBS)
        for li, l in enumerate(layers):
            H = l["h"]
            g = l["w_ih"] @ x + l["b_ih"] + l["w_hh"] @ h[li] + l["b_hh"]
            i_, f_, g_, o_ = sig(g[:H]), sig(g[H:2*H]), np.tanh(g[2*H:3*H]), sig(g[3*H:])
            c[li] = f_ * c[li] + i_ * g_
            h[li] = o_ * np.tanh(c[li])
            x = h[li]
    return sig(hw @ h[-1] + hb)


def torch_forward(ckpt, seq):
    import torch.nn as nn

    class Net(nn.Module):
        def __init__(self, n_in, n_out, hidden=HIDDEN):
            super().__init__()
            self.lstm = nn.LSTM(n_in, hidden, num_layers=2, batch_first=True)
            self.head = nn.Linear(hidden, n_out)

        def forward(self, x):
            out, _ = self.lstm(x)
            return torch.sigmoid(self.head(out[:, -1, :]))

    net = Net(len(ckpt["input_cols"]), 4)
    net.load_state_dict(ckpt["model"])
    net.eval()
    mean = np.asarray(ckpt["feat_mean"])
    std = np.asarray(ckpt["feat_std"])
    seq = seq.copy()
    for c in (ckpt.get("zero_cols", []) or []):
        seq[:, ckpt["input_cols"].index(c)] = 0.0
    x = np.clip((seq - mean) / std, -CLIP_OBS, CLIP_OBS)
    with torch.no_grad():
        return net(torch.tensor(x[None], dtype=torch.float32)).numpy()[0]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lens", default="all")
    ap.add_argument("--n-parity", type=int, default=64)
    ap.add_argument("--install", action="store_true", help="copy into the .drive mod")
    args = ap.parse_args()

    lenses = ([p.parent.name for p in sorted(EXP_DIR.glob("*/model.pt"))]
              if args.lens == "all" else args.lens.split(","))
    print(f"exporting: {lenses}\n")

    rng = np.random.default_rng(0)
    all_ok = True
    for lens in lenses:
        # weights_only=False needed: ckpt carries numpy norm stats and a car_max
        # dict. Safe here - these .pt files are written by our own trainer locally.
        ckpt = torch.load(EXP_DIR / lens / "model.pt", map_location="cpu",
                          weights_only=False)
        text = emit_lua(ckpt, lens)

        worst = 0.0
        n_in, sl = len(ckpt["input_cols"]), ckpt["seq_len"]
        for _ in range(args.n_parity):
            seq = rng.normal(0, 1, size=(sl, n_in)) * np.asarray(ckpt["feat_std"]) \
                  + np.asarray(ckpt["feat_mean"])
            d = np.abs(lua_forward(text, seq) - torch_forward(ckpt, seq)).max()
            worst = max(worst, d)

        ok = worst < 1e-5
        all_ok &= ok
        MOD_CTRL.mkdir(parents=True, exist_ok=True)
        out = MOD_CTRL / f"lstmabs_weights_{lens}.lua"
        if ok:
            out.write_text(text, encoding="utf-8")
        n_nums = text.count(" ") // 1
        print(f"  {lens:14s} parity max|diff|={worst:.3e}  "
              f"{'PASS' if ok else 'FAIL - investigate before deploying!'}  -> {out.name}")

        if args.install and ok:
            DRIVE_CTRL.mkdir(parents=True, exist_ok=True)
            (DRIVE_CTRL / f"lstmabs_weights_{lens}.lua").write_text(text, encoding="utf-8")

    if args.install:
        print(f"\ninstalled to {DRIVE_CTRL}")
    print(f"\n{'ALL PASS' if all_ok else 'SOME FAILED'}")


if __name__ == "__main__":
    main()
